[package]
name = "tetra-launch"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sysinfo = { version = "0.36.1", default-features = false, features = ["system"] }
thiserror.workspace = true
winreg.workspace = true

[lints.rust]
unsafe_code = "forbid"
